-- Archivo conservado por compatibilidad académica.
-- La instalación final MySQL/MariaDB está dividida en:
-- docs/sql/01_source_escall_sp.sql
-- docs/sql/02_target_local_schema.sql
-- docs/sql/03_target_local_views.sql
